# Generated by Django 5.2.5 on 2026-08-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='lote',
            name='telefono',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='lote',
            name='apellido_familia',
            field=models.CharField(max_length=100, verbose_name='Apellido de la familia'),
        ),
    ]
