# Generated by Django 5.2.5 on 2026-08-08 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_lote_usuario_noticia'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='noticias/', verbose_name='Imagen'),
        ),
    ]
