# Generated by Django 5.2.5 on 2026-08-08 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_noticia_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaSUM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de reserva')),
                ('turno', models.CharField(choices=[('dia', 'Turno Día'), ('noche', 'Turno Noche')], max_length=10, verbose_name='Turno')),
                ('cantidad_personas', models.PositiveIntegerField(default=1, verbose_name='Cantidad estimada de personas')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_sum', to='core.lote')),
            ],
            options={
                'verbose_name': 'Reserva del SUM',
                'verbose_name_plural': 'Reservas del SUM',
                'ordering': ['fecha', 'turno'],
                'constraints': [models.UniqueConstraint(fields=('fecha', 'turno'), name='reserva_sum_fecha_turno_unico')],
            },
        ),
    ]
