# Generated by Django 5.2.5 on 2026-08-08 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_reservasum'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reservasum',
            name='reserva_sum_fecha_turno_unico',
        ),
        migrations.AddConstraint(
            model_name='reservasum',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'cancelada'), _negated=True), fields=('fecha', 'turno'), name='reserva_sum_fecha_turno_activo_unico'),
        ),
    ]
