# Generated by Django 5.2.5 on 2026-08-09 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_reservasum_reserva_sum_fecha_turno_unico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudModificacionFamilia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('modificar', 'Modificar datos'), ('alta', 'Agregar integrante'), ('baja', 'Dar de baja integrante'), ('otro', 'Otro')], max_length=20, verbose_name='Tipo de solicitud')),
                ('detalle', models.TextField(verbose_name='Detalle de la solicitud')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('respuesta_administracion', models.TextField(blank=True, verbose_name='Respuesta de administración')),
                ('integrante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_modificacion', to='core.integrante')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_familia', to='core.lote')),
            ],
            options={
                'verbose_name': 'Solicitud de modificación familiar',
                'verbose_name_plural': 'Solicitudes de modificación familiar',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
