# Generated by Django 5.2.5 on 2026-08-09 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_solicitudmodificacionfamilia'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudmodificacionfamilia',
            name='aplicada',
            field=models.BooleanField(default=False, verbose_name='Modificación aplicada'),
        ),
        migrations.AddField(
            model_name='solicitudmodificacionfamilia',
            name='campo_modificar',
            field=models.CharField(blank=True, choices=[('nombre', 'Nombre'), ('apellido', 'Apellido'), ('fecha_nacimiento', 'Fecha de nacimiento'), ('parentesco', 'Parentesco'), ('email', 'Email'), ('telefono', 'Teléfono')], max_length=30, verbose_name='Dato a modificar'),
        ),
        migrations.AddField(
            model_name='solicitudmodificacionfamilia',
            name='nueva_fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento del nuevo integrante'),
        ),
        migrations.AddField(
            model_name='solicitudmodificacionfamilia',
            name='nuevo_apellido',
            field=models.CharField(blank=True, max_length=100, verbose_name='Apellido del nuevo integrante'),
        ),
        migrations.AddField(
            model_name='solicitudmodificacionfamilia',
            name='nuevo_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email del nuevo integrante'),
        ),
        migrations.AddField(
            model_name='solicitudmodificacionfamilia',
            name='nuevo_nombre',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre del nuevo integrante'),
        ),
        migrations.AddField(
            model_name='solicitudmodificacionfamilia',
            name='nuevo_parentesco',
            field=models.CharField(blank=True, max_length=30, verbose_name='Parentesco del nuevo integrante'),
        ),
        migrations.AddField(
            model_name='solicitudmodificacionfamilia',
            name='nuevo_telefono',
            field=models.CharField(blank=True, max_length=30, verbose_name='Teléfono del nuevo integrante'),
        ),
        migrations.AddField(
            model_name='solicitudmodificacionfamilia',
            name='nuevo_valor',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nuevo valor'),
        ),
        migrations.AlterField(
            model_name='solicitudmodificacionfamilia',
            name='detalle',
            field=models.TextField(blank=True, verbose_name='Detalle / comentario'),
        ),
    ]
