# Generated by Django 5.2.5 on 2026-08-09 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_solicitudmodificacionfamilia_aplicada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('iluminacion', 'Iluminación'), ('seguridad', 'Seguridad'), ('calles', 'Calles y circulación'), ('espacios_comunes', 'Espacios comunes'), ('residuos', 'Residuos'), ('mantenimiento', 'Mantenimiento'), ('administracion', 'Administración'), ('otro', 'Otro')], max_length=30, verbose_name='Categoría')),
                ('asunto', models.CharField(max_length=150, verbose_name='Asunto')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('resuelto', 'Resuelto'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('respuesta_administracion', models.TextField(blank=True, verbose_name='Respuesta de Administración')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamos', to='core.lote')),
            ],
            options={
                'verbose_name': 'Reclamo',
                'verbose_name_plural': 'Reclamos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
