# Generated by Django 5.2.5 on 2026-08-09 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_reclamo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encomienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remitente', models.CharField(max_length=150, verbose_name='Empresa / Remitente')),
                ('descripcion', models.CharField(blank=True, max_length=255, verbose_name='Descripción del paquete')),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora de recepción')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de retiro'), ('entregada', 'Entregada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de entrega')),
                ('retirado_por', models.CharField(blank=True, max_length=150, verbose_name='Retirado por')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encomiendas', to='core.lote')),
            ],
            options={
                'verbose_name': 'Encomienda',
                'verbose_name_plural': 'Encomiendas',
                'ordering': ['-fecha_recepcion'],
            },
        ),
    ]
