# Generated by Django 5.2.5 on 2026-08-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_encomienda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('categoria', models.CharField(choices=[('reglamento', 'Reglamento'), ('administracion', 'Administración'), ('sum', 'SUM'), ('seguridad', 'Seguridad'), ('obras', 'Obras'), ('expensas', 'Expensas'), ('otro', 'Otro')], max_length=30, verbose_name='Categoría')),
                ('archivo', models.FileField(upload_to='documentos/', verbose_name='Archivo')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de publicación')),
                ('activo', models.BooleanField(default=True, verbose_name='Visible para los vecinos')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
