# Generated by Django 5.2.5 on 2026-08-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoUtil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('seguridad', 'Seguridad'), ('emergencias', 'Emergencias'), ('administracion', 'Administración'), ('mantenimiento', 'Mantenimiento'), ('servicios', 'Servicios'), ('otro', 'Otro')], max_length=30, verbose_name='Categoría')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('telefono', models.CharField(max_length=50, verbose_name='Teléfono')),
                ('whatsapp', models.CharField(blank=True, max_length=50, verbose_name='WhatsApp')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Visible para los vecinos')),
            ],
            options={
                'verbose_name': 'Contacto útil',
                'verbose_name_plural': 'Contactos útiles',
                'ordering': ['orden', 'categoria', 'nombre'],
            },
        ),
    ]
