# Generated by Django 5.2.5 on 2026-09-01 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_contactoutil'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitadoFrecuente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('dni', models.CharField(max_length=20, verbose_name='DNI')),
                ('patente', models.CharField(blank=True, max_length=20, verbose_name='Patente')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitados_frecuentes', to='core.lote')),
            ],
            options={
                'verbose_name': 'Invitado frecuente',
                'verbose_name_plural': 'Invitados frecuentes',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('dni', models.CharField(max_length=20, verbose_name='DNI')),
                ('patente', models.CharField(blank=True, max_length=20, verbose_name='Patente')),
                ('fecha', models.DateField(verbose_name='Fecha de visita')),
                ('evento', models.CharField(blank=True, max_length=150, verbose_name='Evento / Motivo')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('estado', models.CharField(choices=[('autorizada', 'Autorizada'), ('cancelada', 'Cancelada')], default='autorizada', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('invitado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas', to='core.invitadofrecuente')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='core.lote')),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
                'ordering': ['-fecha', '-fecha_creacion'],
            },
        ),
    ]
