# Generated by Django 5.2.5 on 2026-09-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_invitadofrecuente_visita'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='fecha_hora_ingreso',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de ingreso'),
        ),
        migrations.AddField(
            model_name='visita',
            name='fecha_hora_salida',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de salida'),
        ),
    ]
