# Generated by Django 5.2.5 on 2026-09-05 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_visita_fecha_hora_ingreso_visita_fecha_hora_salida'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservasum',
            name='solicitado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_sum_solicitadas', to='core.integrante', verbose_name='Solicitado por'),
        ),
    ]
