# Generated by Django 5.2.5 on 2026-09-09 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_reservasum_solicitado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactoutil',
            name='categoria',
            field=models.CharField(choices=[('seguridad', 'Seguridad'), ('emergencias', 'Emergencias'), ('administracion', 'Administración'), ('intendencia', 'Intendencia'), ('mantenimiento', 'Mantenimiento'), ('servicios', 'Servicios'), ('otro', 'Otro')], max_length=30, verbose_name='Categoría'),
        ),
    ]
