# Generated by Django 5.2.5 on 2026-09-10 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_contactoutil_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('robo', 'Robo'), ('incendio', 'Incendio'), ('medica', 'Emergencia médica'), ('accidente', 'Accidente'), ('otra', 'Otra')], max_length=20, verbose_name='Tipo de emergencia')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción / información adicional')),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('atendida', 'Atendida por Portería'), ('cerrada', 'Cerrada')], default='activa', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora de activación')),
                ('fecha_atencion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de atención')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de cierre')),
                ('observaciones_porteria', models.TextField(blank=True, verbose_name='Observaciones de Portería')),
                ('atendida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergencias_atendidas', to=settings.AUTH_USER_MODEL, verbose_name='Atendida por')),
                ('cerrada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergencias_cerradas', to=settings.AUTH_USER_MODEL, verbose_name='Cerrada por')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergencias', to='core.lote')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergencias_generadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que generó la alerta')),
            ],
            options={
                'verbose_name': 'Emergencia',
                'verbose_name_plural': 'Emergencias',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
