# Generated by Django 5.2.5 on 2026-09-10 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_emergencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('encomienda', 'Encomienda'), ('sum', 'Reserva SUM'), ('reclamo', 'Reclamo'), ('familia', 'Mi familia'), ('general', 'General')], default='general', max_length=20, verbose_name='Tipo')),
                ('titulo', models.CharField(max_length=180, verbose_name='Título')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('url', models.CharField(blank=True, max_length=255, verbose_name='Destino')),
                ('leida', models.BooleanField(default=False, verbose_name='Leída')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='core.lote')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
